name = "Bloons TD6"
home = "https://github.com/Matt41321/Archipelago"
default_url = "https://github.com/Matt41321/Archipelago/releases/download/v{{version}}/bloonstd6.apworld"

[versions]
"0.2.3" = { url = "https://github.com/GamingInfinite/Archipelago/releases/download/0.2.3.0/bloonstd6.apworld" }
"0.3.3" = { url = "https://github.com/GamingInfinite/Archipelago/releases/download/0.3.3.0/bloonstd6.apworld" }
"0.7.1" = {}
