name = "Celeste (Open World)"
home = "https://ovapelago.sylvanova.gg"
default_url = "https://github.com/PoryGoneDev/Celeste-Archipelago-Open-World/releases/download/v{{version}}/celeste_open_world.apworld"

[versions]
"1.0.7" = {}
"1.1.1" = {}
"1.1.2" = {}
"1.1.3" = {}
