name = "Cyberpunk 2077"
home = "https://github.com/247Tossing/cyberpunk_archipelago"
default_url = "https://github.com/247Tossing/cyberpunk_archipelago/releases/download/0.7.1/cyberpunk2077-{{version}}.apworld"

[versions]
"0.7.0" = { url = "https://github.com/247Tossing/cyberpunk_archipelago/releases/download/0.7.0/cyberpunk2077.apworld" }
"0.7.1" = {}
