name = "Dark Souls III"
home = "https://ovapelago.sylvanova.gg"
supported = true
# DS3's way of not randomizing filler requires people to use AP's local_items
# which does **NOT** scale at all and creates many headaches since it fails post
# fill and forces us to remove local items to even get gens.
disabled = true
