name = "Factorio: Space Age"
home = "https://github.com/thejoshwolfe/Archipelago"
default_url = "https://github.com/thejoshwolfe/Archipelago/releases/download/space-age-v{{version}}/factorio_space_age.apworld"

[versions]
"2.2.3" = {}
"2.2.4" = {}
"2.3.0" = {}
"2.3.1" = {}
