name = "Pokemon Black and White"
home = "https://github.com/BlastSlimey/PokemonBWAP"
default_url = "https://github.com/BlastSlimey/PokemonBWAP/releases/download/{{version}}/pokemon_bw.apworld"

[versions]
"0.3.17" = { url = "https://github.com/BlastSlimey/PokemonBWAP/releases/download/0.3.17/pokemon_bw_without_maps.apworld" }
"0.3.14" = { url = "https://github.com/BlastSlimey/PokemonBWAP/releases/download/0.3.14/pokemon_bw_without_maps.apworld" }
"0.3.13" = { url = "https://github.com/BlastSlimey/PokemonBWAP/releases/download/0.3.13/pokemon_bw_without_maps.apworld" }
"0.3.37" = {}
