name = "Rimworld"
home = "https://github.com/PhantomOfAres/ArchipelagoRimworld"
default_url = "https://github.com/PhantomOfAres/ArchipelagoRimworld/releases/download/v{{version}}/rimworld.apworld"

[versions]
"0.5.2-bugfix" = {}
"0.1.0-alpha" = {}
"0.1.1-alpha" = {}
"0.2.0-alpha" = {}
"0.3.0-alpha" = {}
"0.3.2-alpha" = {}
"0.4.0-alpha" = {}
"0.4.2-alpha" = {}
"0.4.3-alpha" = {}
"0.5.0-alpha" = {}
