archipelago_repo = "https://github.com/ArchipelagoMW/Archipelago.git"
archipelago_version = "0.6.7"
index_homepage = "https://github.com/SylvaNova-Developers/SylvaNova-Archipelago-Index"
index_dir = "index"
